module.exports = [
  {
    Grupo: "A-1-1-1-1",
    Líder: "Javier Ruiz",
    Teléfono: ["702-326-3195"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: ["Todos Bienvenidos"],
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "A-2-1-2-1",
    Líder: "Fernando Ayala",
    Teléfono: ["702-472-4427"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: ["Matrimonios Sin Hijos"],
    Tiempo: ["7:15 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "A-2-1-2-1",
    Líder: "Henry Villaneuva",
    Teléfono: ["702-886-6788"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: ["Matrimonios Mixtas"],
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "A-2-1-3-2",
    Líder: "Henry Vasquez",
    Teléfono: ["702-666-4293"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "A-2-1-5-1",
    Líder: "Jose L. Agustin",
    Teléfono: ["702-773-4022"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "A-2-4-1-1",
    Líder: "Lucia Villaneuva",
    Teléfono: ["702-533-8209"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["4:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "A-3-1-1-1",
    Líder: "Mirna Lopez",
    Teléfono: ["702-406-8549"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (14-21 Años)",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "A-5-2-1-1",
    Líder: "Carlos Alvarez",
    Teléfono: ["702-689-6905"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "A-5-2-1-2",
    Líder: "Carlos Alvarez",
    Teléfono: ["702-689-6905"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Solteros)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-1-4-1",
    Líder: "Yazmina Hernandez",
    Teléfono: ["702-418-6621"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-2-1-1",
    Líder: "Jaime Avila",
    Teléfono: ["702-769-0726"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-1-2-1-1",
    Líder: "Isidro Rodriguez",
    Teléfono: ["702-969-4087"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-2-1-2",
    Líder: "Isidro Rodriguez",
    Teléfono: ["702-969-4087"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-2-2-2",
    Líder: "Juan y Barbara Banuelos",
    Teléfono: ["702-296-9744", "702-326-3771"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-3-2-2",
    Líder: "Albina Cervantes",
    Teléfono: ["702-272-3196"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-1-3-3-1",
    Líder: "Narciso y Angelina Cervantez",
    Teléfono: ["702-466-4142", "702-767-8575"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-1-3-3-2",
    Líder: "Maria Mendoza",
    Teléfono: ["702-684-2260"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-1-4-1-2",
    Líder: "Rodolfo Hernandez",
    Teléfono: ["702-619-8006"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-1-4-3-2",
    Líder: "Eduardo Contreras",
    Teléfono: ["702-349-8282"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-2-1-1-1",
    Líder: "Catalina Escobedo",
    Teléfono: ["702-684-2319"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-2-1-1-2",
    Líder: "Elizabeth Gonzalez",
    Teléfono: ["702-490-2679"],
    Ubicación: "Las Vegas",
    Dias: "Martes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["4:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-2-1-2-1",
    Líder: "Sandra Martinez",
    Teléfono: ["702-772-4758"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-2-1-2-1",
    Líder: "Juan Colin",
    Teléfono: ["916-317-6427"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-2-2-2-1",
    Líder: "Ivan Garcia",
    Teléfono: ["702-409-5279"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-3-1-2-1",
    Líder: "Raul Ruiz",
    Teléfono: ["702-448-0210"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-3-1-3-1",
    Líder: "Maurilio Rosas",
    Teléfono: ["702-980-5519"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-3-2-2-2",
    Líder: "Sergio y Sandra Cardona",
    Teléfono: ["702-929-8548", "702-545-5424"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-3-3-1-1",
    Líder: "Rosa M. Melara",
    Teléfono: ["702-812-1664"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-3-5-1-1",
    Líder: "Toribio Ortiz",
    Teléfono: ["702-806-3215"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-3-5-1-2",
    Líder: "Gloria Chavez",
    Teléfono: ["702-504-0148"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-3-5-2-1",
    Líder: "Roman Cruz Ortiz",
    Teléfono: ["725-300-1554"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-3-5-2-2",
    Líder: "Silvia Cruz",
    Teléfono: ["725-266-2852"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-4-1-1-1",
    Líder: "Matilde Enriquez",
    Teléfono: ["702-502-2062"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-4-1-1-2",
    Líder: "Mirian Murcia",
    Teléfono: ["702-561-8836"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-4-1-2-1",
    Líder: "Margarita Franco",
    Teléfono: ["725-203-8602"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "J-4-1-2-2",
    Líder: "Rafael Carrera",
    Teléfono: ["702-583-9660"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["11:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "J-4-1-3-1",
    Líder: "Magali Quiroa",
    Teléfono: ["702-544-5536"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-1-1-1",
    Líder: "Jaziel Sanchez",
    Teléfono: ["702-544-5536"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Hombres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-1-2-1",
    Líder: "Astrid Palomo",
    Teléfono: ["702-559-3984"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Mujeres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-1-3-1",
    Líder: "Jesse Campos",
    Teléfono: ["702-373-6126", "702-846-8301"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Hombres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-2-1-1",
    Líder: "Edwin Garcia",
    Teléfono: ["661-916-4145"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-2-1-2",
    Líder: "David Cruz",
    Teléfono: ["702-504-9499"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Hombres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-3",
    Líder: "Chrisopher Sanchez",
    Teléfono: ["702-918-9530"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-3-1-1",
    Líder: "Felix Sanchez Jr",
    Teléfono: ["702-801-9381"],
    Ubicación: "Las Vegas",
    Dias: "Domingo",
    Género: "Hombres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["3:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "N-1-4-1-2",
    Líder: "Tania Diaz",
    Teléfono: ["702-287-9489"],
    Ubicación: "Las Vegas",
    Dias: "Domingo",
    Género: "Mujeres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["12:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-1-4-4-1",
    Líder: "Dennise Castillo",
    Teléfono: ["702-592-1373"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["5:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-2-1-4-1",
    Líder: "Leyla Nunez",
    Teléfono: ["702-287-9339"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "N-2-2-4-2",
    Líder: "Denisse Zelaya",
    Teléfono: ["702-858-4416"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-2-3-2-2",
    Líder: "Alex Ortega",
    Teléfono: ["702-321-2854"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-2-3-3-2",
    Líder: "Victor Portillo",
    Teléfono: ["702-845-6952"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-1-1",
    Líder: "Quitzia Abigail Soto",
    Teléfono: ["702-502-7737"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-1-2",
    Líder: "Isaac Soto",
    Teléfono: ["702-502-7988"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-2-1",
    Líder: "Diego Saravia",
    Teléfono: ["702-917-1932"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-2-2",
    Líder: "Jonathan Penate",
    Teléfono: ["702-272-3673"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-3-1",
    Líder: "Nori Castillo",
    Teléfono: ["702-272-9592"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-3-1-3-2",
    Líder: "Tracy Saravia",
    Teléfono: ["702-629-8390"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "N-3-1-4-1",
    Líder: "Yamile Vasquez",
    Teléfono: ["702-300-6710"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["5:30 PM"],
    EnPersona: "En Persona",
    Idioma: "",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-4-1-1-1",
    Líder: "Maria Gonzalez",
    Teléfono: ["702-980-4820"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-4-1-1-2",
    Líder: "Armando Perez",
    Teléfono: ["725-266-2083"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Hombres",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-4-2-2-1",
    Líder: "Jose Manuel Garcia",
    Teléfono: ["702-665-3813"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "N-4-2-2-2",
    Líder: "Raul Ramirez",
    Teléfono: ["702-665-3209"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Jovenes)",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-1-1-1-2",
    Líder: "Ronald Portillo",
    Teléfono: ["702-517-0017"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-1-1-4-2",
    Líder: "Maria Gonzalez",
    Teléfono: ["702-353-9575"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-1-2-1-1",
    Líder: "Carmen Huerta",
    Teléfono: ["702-521-5359"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-1-2-3-2",
    Líder: "Deysi Ayala",
    Teléfono: ["702-517-8461"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-1-3-1-2",
    Líder: "Antonia Buatista",
    Teléfono: ["702-375-0414"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-1-3-2-1",
    Líder: "Silvia Solis",
    Teléfono: ["702-505-6044"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-1-1-1",
    Líder: "Isidro Escobar",
    Teléfono: ["702-497-0366"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-1-4-1",
    Líder: "Maria E. Avila",
    Teléfono: ["702-470-3277"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-1-1",
    Líder: "Eusebio Duran",
    Teléfono: ["702-470-3277"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-2-1-2",
    Líder: "Azucena Neria",
    Teléfono: ["702-813-3706"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-2-1",
    Líder: "Roberto Lopez",
    Teléfono: ["702-813-3706"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-2-2",
    Líder: "Eusebia Garcia",
    Teléfono: ["702-689-1736"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-2-3-1",
    Líder: "Luis Hernandez",
    Teléfono: ["702-628-2928"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-2-3-2",
    Líder: "Daniela Lopez",
    Teléfono: ["310-920-4978"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Inglés",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-4-1",
    Líder: "Daniel Perez",
    Teléfono: ["702-937-5859"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-4-1",
    Líder: "Daniel Perez",
    Teléfono: ["702-937-5859"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-2-5-1",
    Líder: "Rigoberto Hernandez",
    Teléfono: ["702-883-9018"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Jovenes 14-21 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-2-3-1-1",
    Líder: "Leticia De Rivera",
    Teléfono: ["702-221-6412"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-2-3-1-2",
    Líder: "Nicasio Duran",
    Teléfono: [""],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-3-1-2-2",
    Líder: "Maribel Ayala",
    Teléfono: ["702-752-4330"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-3-1-4-2",
    Líder: "Ana Vazquez",
    Teléfono: ["702-628-2751"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-3-1-5-1",
    Líder: "Javier y Ofelia Limon",
    Teléfono: ["702-488-4232", "702-406-8881"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-3-2-1-2",
    Líder: "Jose Urias",
    Teléfono: ["702-955-0020"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-3-2-2-2",
    Líder: "Kiara Prado",
    Teléfono: ["702-849-8239"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Mixtas (Solteros) 22-35 Años",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-4-3-2-1",
    Líder: "Anabel Martinez",
    Teléfono: ["702-624-2275"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-4-3-3-2",
    Líder: "Blas Duran",
    Teléfono: ["702-502-2773"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-4-4-1-1",
    Líder: "Alejandra Rodriguez",
    Teléfono: ["702-410-3674"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-4-4-1-2",
    Líder: "Margarita Hernandez",
    Teléfono: ["702-328-4825"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "R-4-4-2-2",
    Líder: "Antonio Fernandez",
    Teléfono: ["702-937-2613"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "R-4-4-3-1",
    Líder: "Isabel Calix",
    Teléfono: ["702-849-3085"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-1-1-3-2",
    Líder: "Armando y Olga Lopez",
    Teléfono: ["702-406-4311"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-1-2-2-1",
    Líder: "Gabriel Chavez",
    Teléfono: ["702-793-0131"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-1-3-2-2",
    Líder: "Jose A. Martinez",
    Teléfono: ["702-503-9660"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (14-21 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-1-4-1-1",
    Líder: "Alejandro Rubio",
    Teléfono: ["702-376-5660"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-1-4-1-2",
    Líder: "Antonio Hernandez",
    Teléfono: ["702-931-6657"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Matrimonios Sin Hijos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-2-2-4-1",
    Líder: "Dulce Sanchez",
    Teléfono: ["702-513-4475"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-2-3-1-2",
    Líder: "Ana Escobar",
    Teléfono: ["702-517-0798"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-2-3-5-1",
    Líder: "Maria Sandoval",
    Teléfono: ["702-628-4769"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["10:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-2-3-5-2",
    Líder: "Blanca Vargas",
    Teléfono: ["702-412-2784"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-2-5-2-1",
    Líder: "Basilio Martin",
    Teléfono: ["702-752-4259"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-2-5-2-2",
    Líder: "Maria C. Garcia",
    Teléfono: ["661-886-3358"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-2-5-3-1",
    Líder: "Pascasio y Lucina Martin",
    Teléfono: ["702-463-0341"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-3-1-1-1",
    Líder: "Judith Melgar",
    Teléfono: ["702-419-6193"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-3-1-2-1",
    Líder: "Marcos Berrut",
    Teléfono: ["702-919-9914"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-3-3-1-1",
    Líder: "Erika Beltran",
    Teléfono: ["702-675-0938"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-3-3-1-2",
    Líder: "Ismael Martin",
    Teléfono: ["702-494-9281"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (14-21 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-3-4-1-2",
    Líder: "Rosa Nelson",
    Teléfono: ["702-370-0585"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-4-1-1-1",
    Líder: "Yessica Estrada",
    Teléfono: ["702-772-5150"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-4-1-1-2",
    Líder: "Jose Estrada",
    Teléfono: ["702-908-0326"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-4-2-1-1",
    Líder: "Juan Tiznado",
    Teléfono: ["725-600-1447"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-4-2-1-2",
    Líder: "Melina Marin",
    Teléfono: ["702-680-5966"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-4-2-2-1",
    Líder: "Cesar Solano",
    Teléfono: ["702-479-9082"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles/Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-4-2-3-1",
    Líder: "Lupita Solano",
    Teléfono: ["702-583-0952"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-5-1-1-1",
    Líder: "Veronica Castro",
    Teléfono: ["702-972-5308"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Mujeres",
    Demográfico: "Mujeres Solteras (36-60 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-5-1-1-2",
    Líder: "Johony Ceron",
    Teléfono: ["702-755-3671"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-5-2-1-1",
    Líder: "Lidia Hernandez",
    Teléfono: ["702-759-3465"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-5-2-1-2",
    Líder: "Rosa Gonzalez",
    Teléfono: ["209-594-2823"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["11:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "S-5-3-1-1",
    Líder: "Conny Rendon",
    Teléfono: ["702-569-1662"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "S-5-3-1-2",
    Líder: "Ivania Moreno",
    Teléfono: ["702-287-6542"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-1-1-1",
    Líder: "Gina Cobas",
    Teléfono: ["702-758-0244"],
    Ubicación: "Las Vegas",
    Dias: "Martes",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["10:30 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-1-1-2",
    Líder: "Johanna Largaespada",
    Teléfono: ["661-916-1067"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-1-1-2-1",
    Líder: "Alex Gonzalez",
    Teléfono: ["702-533-6851"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-1-3-2",
    Líder: "Higinio Gomez",
    Teléfono: ["702-980-2713"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-3-1-1",
    Líder: "Alejandra Osorio",
    Teléfono: ["323-504-0396"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Mixtas (Solteros) 22-35 Años",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-3-2-1",
    Líder: "Clara Nieto",
    Teléfono: ["702-541-5868"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-3-3-1",
    Líder: "Fabiola Esparza",
    Teléfono: ["702-824-7777"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico:
      "Matrimonios Con Hijos (0-8 Años) Matrimonios Con Hijos (14-21 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-3-3-2",
    Líder: "Francisco Osorio",
    Teléfono: ["323-499-8288"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-1-3-4-1",
    Líder: "Cecilia Sheffer",
    Teléfono: ["702-773-9967"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["5:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-1-3-4-2",
    Líder: "Gerardo y Cristal Salas",
    Teléfono: ["702-401-2997"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Mujeres",
    Demográfico: "Mujeres Solteras",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-3-5-1",
    Líder: "Cecilia Sheffer",
    Teléfono: ["702-773-9967"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["11:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Bilingüe",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-5",
    Líder: "Elena Gomez",
    Teléfono: ["702-488-5131"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-1-5-1-1",
    Líder: "Elena Gomez",
    Teléfono: ["702-488-5131"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["10:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-2-1-1-1",
    Líder: "Maria E.Herrera",
    Teléfono: ["702-675-0406"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-2-3-1-1",
    Líder: "Jorge Gonzalez",
    Teléfono: ["702-504-5736", "702-542-9347"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-2-3-1-2",
    Líder: "Laura Galvez",
    Teléfono: ["702-209-7964"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-2-3-3-1",
    Líder: "Cecilia Villalta",
    Teléfono: ["702-666-1052"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-2-4-1-1",
    Líder: "Roberto Salgado",
    Teléfono: ["562-477-1126"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-2-4-2-1",
    Líder: "Miriam Escalante",
    Teléfono: ["702-845-8333"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-2-4-2-2",
    Líder: "Oscar Perez",
    Teléfono: ["702-912-9042"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-3-1-1-1",
    Líder: "Erika Marin",
    Teléfono: ["702-418-4470"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-3-1-2-1",
    Líder: "Erika Marin",
    Teléfono: ["702-418-4470"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["9:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-3-2-1-1",
    Líder: "Jose Corral",
    Teléfono: ["702-300-6878"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["6:30 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-3-2-2-2",
    Líder: "Eliseo y Carmen Pascual",
    Teléfono: ["702-773-1150", "702-787-1547"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["8:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-3-3-1-1",
    Líder: "Alvin y Alicia Rodriguez",
    Teléfono: ["702-913-0006", "702-502-0743"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-3-3-2-1",
    Líder: "Rosa Zelaya",
    Teléfono: ["702-324-5373", "702-494-9239"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Mixtas",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-3-4-1-1",
    Líder: "Juan y Ruth Ventura",
    Teléfono: ["702-501-2847", "702-496-1780"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-3-4-1-2",
    Líder: "Norma Ramos y Francisco Sanchez",
    Teléfono: ["702-682-7147", "702-412-9191"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-3-5-1-1",
    Líder: "Juan Cuaya",
    Teléfono: ["702-771-8962", "702-773-5977"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-1-1-2",
    Líder: "Erick Castillo",
    Teléfono: ["702-773-5701"],
    Ubicación: "Las Vegas",
    Dias: "Sábado",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["10:00 AM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-1-2-2",
    Líder: "Norma Castillo",
    Teléfono: ["702-479-9331"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-4-1-4-1",
    Líder: "Angel Gonzalez",
    Teléfono: ["702-595-8579", "702-624-1281"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-2-1-2",
    Líder: "Olga y Jaime Leon",
    Teléfono: ["702-500-9433", "702-582-1006"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-3-1-2",
    Líder: "Martha Sotelo",
    Teléfono: ["702-809-6566"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-4-1-1",
    Líder: "Heraclio Antonio Zerafino",
    Teléfono: ["702-772-5886"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-4-5-2-2",
    Líder: "Yanet Rodriguez",
    Teléfono: ["702-980-6413"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-5-1-1-1",
    Líder: "Hedilberto Avalos",
    Teléfono: ["702-937-0043"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-5-1-1-2",
    Líder: "Carlos Acosta",
    Teléfono: ["702-609-1917"],
    Ubicación: "Las Vegas",
    Dias: "Lunes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["6:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
  {
    Grupo: "SH-5-2-1-1",
    Líder: "Jeorgina Torres Pena",
    Teléfono: ["702-504-7007"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (Todos Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-5-2-1-2",
    Líder: "Griselda Flores",
    Teléfono: ["702-217-1079"],
    Ubicación: "Las Vegas",
    Dias: "Miércoles",
    Género: "Combinados",
    Demográfico: "Matrimonios Con Hijos (0-8 Años)",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-5-2-1-2",
    Líder: "William Flores",
    Teléfono: ["702-858-0661"],
    Ubicación: "Las Vegas",
    Dias: "Jueves",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "NiñosBienvenidos",
  },
  {
    Grupo: "SH-5-3-2-1",
    Líder: "Claudia Elizabeth Aguilar",
    Teléfono: ["702-504-8017"],
    Ubicación: "Las Vegas",
    Dias: "Viernes",
    Género: "Combinados",
    Demográfico: "Todos Bienvenidos",
    Tiempo: ["7:00 PM"],
    EnPersona: "En Persona",
    Idioma: "Español",
    NiñosBienvenidos: "No",
  },
];
