module.exports = [
  {
    Group: "A-1-1-1-1",
    Leader: "Javier Ruiz",
    Phone: ["702-326-3195"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: ["Everyone Welcome"],
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "A-2-1-2-1",
    Leader: "Fernando Ayala",
    Phone: ["702-472-4427"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: ["Married Without Children"],
    Time: ["7:15 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "A-2-1-2-1",
    Leader: "Henry Villaneuva",
    Phone: ["702-886-6788"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: ["Married Couples (Mixed)"],
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "A-2-1-3-2",
    Leader: "Henry Vasquez",
    Phone: ["702-666-4293"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "A-2-1-5-1",
    Leader: "Jose L. Agustin",
    Phone: ["702-773-4022"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "A-2-4-1-1",
    Leader: "Lucia Villaneuva",
    Phone: ["702-533-8209"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["4:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "A-3-1-1-1",
    Leader: "Mirna Lopez",
    Phone: ["702-406-8549"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Married With Children (14-21 years)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "A-5-2-1-1",
    Leader: "Carlos Alvarez",
    Phone: ["702-689-6905"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "A-5-2-1-2",
    Leader: "Carlos Alvarez",
    Phone: ["702-689-6905"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Coed",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-1-4-1",
    Leader: "Yazmina Hernandez",
    Phone: ["702-418-6621"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-2-1-1",
    Leader: "Jaime Avila",
    Phone: ["702-769-0726"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-1-2-1-1",
    Leader: "Isidro Rodriguez",
    Phone: ["702-969-4087"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-2-1-2",
    Leader: "Isidro Rodriguez",
    Phone: ["702-969-4087"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-2-2-2",
    Leader: "Juan y Barbara Banuelos",
    Phone: ["702-296-9744", "702-326-3771"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-3-2-2",
    Leader: "Albina Cervantes",
    Phone: ["702-272-3196"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-1-3-3-1",
    Leader: "Narciso y Angelina Cervantez",
    Phone: ["702-466-4142", "702-767-8575"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-1-3-3-2",
    Leader: "Maria Mendoza",
    Phone: ["702-684-2260"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-1-4-1-2",
    Leader: "Rodolfo Hernandez",
    Phone: ["702-619-8006"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-1-4-3-2",
    Leader: "Eduardo Contreras",
    Phone: ["702-349-8282"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-2-1-1-1",
    Leader: "Catalina Escobedo",
    Phone: ["702-684-2319"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-2-1-1-2",
    Leader: "Elizabeth Gonzalez",
    Phone: ["702-490-2679"],
    Campus: "Las Vegas",
    Days: "Tuesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["4:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-2-1-2-1",
    Leader: "Sandra Martinez",
    Phone: ["702-772-4758"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-2-1-2-1",
    Leader: "Juan Colin",
    Phone: ["916-317-6427"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-2-2-2-1",
    Leader: "Ivan Garcia",
    Phone: ["702-409-5279"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-3-1-2-1",
    Leader: "Raul Ruiz",
    Phone: ["702-448-0210"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-3-1-3-1",
    Leader: "Maurilio Rosas",
    Phone: ["702-980-5519"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-3-2-2-2",
    Leader: "Sergio y Sandra Cardona",
    Phone: ["702-929-8548", "702-545-5424"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-3-3-1-1",
    Leader: "Rosa M. Melara",
    Phone: ["702-812-1664"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-3-5-1-1",
    Leader: "Toribio Ortiz",
    Phone: ["702-806-3215"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-3-5-1-2",
    Leader: "Gloria Chavez",
    Phone: ["702-504-0148"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-3-5-2-1",
    Leader: "Roman Cruz Ortiz",
    Phone: ["725-300-1554"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-3-5-2-2",
    Leader: "Silvia Cruz",
    Phone: ["725-266-2852"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-4-1-1-1",
    Leader: "Matilde Enriquez",
    Phone: ["702-502-2062"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-4-1-1-2",
    Leader: "Mirian Murcia",
    Phone: ["702-561-8836"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-4-1-2-1",
    Leader: "Margarita Franco",
    Phone: ["725-203-8602"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "J-4-1-2-2",
    Leader: "Rafael Carrera",
    Phone: ["702-583-9660"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["11:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "J-4-1-3-1",
    Leader: "Magali Quiroa",
    Phone: ["702-544-5536"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "N-1-1-1-1",
    Leader: "Jaziel Sanchez",
    Phone: ["702-544-5536"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Male",
    Demographic: "Youth (14-21)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-1-2-1",
    Leader: "Astrid Palomo",
    Phone: ["702-559-3984"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Female",
    Demographic: "Youth (14-21)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-1-3-1",
    Leader: "Jesse Campos",
    Phone: ["702-373-6126", "702-846-8301"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Male",
    Demographic: "Youth (14-21)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-2-1-1",
    Leader: "Edwin Garcia",
    Phone: ["661-916-4145"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-2-1-2",
    Leader: "David Cruz",
    Phone: ["702-504-9499"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Male",
    Demographic: "Youth (14-21)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-3",
    Leader: "Chrisopher Sanchez",
    Phone: ["702-918-9530"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-1-3-1-1",
    Leader: "Felix Sanchez Jr",
    Phone: ["702-801-9381"],
    Campus: "Las Vegas",
    Days: "Sunday",
    Gender: "Male",
    Demographic: "Youth (14-21)",
    Time: ["3:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "Childcare",
  },
  {
    Group: "N-1-4-1-2",
    Leader: "Tania Diaz",
    Phone: ["702-287-9489"],
    Campus: "Las Vegas",
    Days: "Sunday",
    Gender: "Female",
    Demographic: "Youth (14-21)",
    Time: ["12:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "N-1-4-4-1",
    Leader: "Dennise Castillo",
    Phone: ["702-592-1373"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["5:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-2-1-4-1",
    Leader: "Leyla Nunez",
    Phone: ["702-287-9339"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "Childcare",
  },
  {
    Group: "N-2-2-4-2",
    Leader: "Denisse Zelaya",
    Phone: ["702-858-4416"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-2-3-2-2",
    Leader: "Alex Ortega",
    Phone: ["702-321-2854"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-2-3-3-2",
    Leader: "Victor Portillo",
    Phone: ["702-845-6952"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "N-3-1-1-1",
    Leader: "Quitzia Abigail Soto",
    Phone: ["702-502-7737"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "N-3-1-1-2",
    Leader: "Isaac Soto",
    Phone: ["702-502-7988"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Youth (14-21)",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "N-3-1-2-1",
    Leader: "Diego Saravia",
    Phone: ["702-917-1932"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-3-1-2-2",
    Leader: "Jonathan Penate",
    Phone: ["702-272-3673"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "N-3-1-3-1",
    Leader: "Nori Castillo",
    Phone: ["702-272-9592"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Youth (14-21)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-3-1-3-2",
    Leader: "Tracy Saravia",
    Phone: ["702-629-8390"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "",
    Childcare: "Childcare",
  },
  {
    Group: "N-3-1-4-1",
    Leader: "Yamile Vasquez",
    Phone: ["702-300-6710"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["5:30 PM"],
    InPerson: "In-Person",
    Language: "",
    Childcare: "No",
  },
  {
    Group: "N-4-1-1-1",
    Leader: "Maria Gonzalez",
    Phone: ["702-980-4820"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-4-1-1-2",
    Leader: "Armando Perez",
    Phone: ["725-266-2083"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Male",
    Demographic: "Youth (14-21)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "N-4-2-2-1",
    Leader: "Jose Manuel Garcia",
    Phone: ["702-665-3813"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "N-4-2-2-2",
    Leader: "Raul Ramirez",
    Phone: ["702-665-3209"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "All Youth",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-1-1-1-2",
    Leader: "Ronald Portillo",
    Phone: ["702-517-0017"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-1-1-4-2",
    Leader: "Maria Gonzalez",
    Phone: ["702-353-9575"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-1-2-1-1",
    Leader: "Carmen Huerta",
    Phone: ["702-521-5359"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-1-2-3-2",
    Leader: "Deysi Ayala",
    Phone: ["702-517-8461"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-1-3-1-2",
    Leader: "Antonia Buatista",
    Phone: ["702-375-0414"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-1-3-2-1",
    Leader: "Silvia Solis",
    Phone: ["702-505-6044"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-1-1-1",
    Leader: "Isidro Escobar",
    Phone: ["702-497-0366"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-1-4-1",
    Leader: "Maria E. Avila",
    Phone: ["702-470-3277"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-2-1-1",
    Leader: "Eusebio Duran",
    Phone: ["702-470-3277"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-2-1-2",
    Leader: "Azucena Neria",
    Phone: ["702-813-3706"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-2-2-1",
    Leader: "Roberto Lopez",
    Phone: ["702-813-3706"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-2-2-2",
    Leader: "Eusebia Garcia",
    Phone: ["702-689-1736"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-2-3-1",
    Leader: "Luis Hernandez",
    Phone: ["702-628-2928"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-2-3-2",
    Leader: "Daniela Lopez",
    Phone: ["310-920-4978"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "English",
    Childcare: "No",
  },
  {
    Group: "R-2-2-4-1",
    Leader: "Daniel Perez",
    Phone: ["702-937-5859"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Youth (14-21)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-2-4-1",
    Leader: "Daniel Perez",
    Phone: ["702-937-5859"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Youth (14-21)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-2-5-1",
    Leader: "Rigoberto Hernandez",
    Phone: ["702-883-9018"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Youth (14-21)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-2-3-1-1",
    Leader: "Leticia De Rivera",
    Phone: ["702-221-6412"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-2-3-1-2",
    Leader: "Nicasio Duran",
    Phone: [""],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-3-1-2-2",
    Leader: "Maribel Ayala",
    Phone: ["702-752-4330"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-3-1-4-2",
    Leader: "Ana Vazquez",
    Phone: ["702-628-2751"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-3-1-5-1",
    Leader: "Javier y Ofelia Limon",
    Phone: ["702-488-4232", "702-406-8881"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-3-2-1-2",
    Leader: "Jose Urias",
    Phone: ["702-955-0020"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-3-2-2-2",
    Leader: "Kiara Prado",
    Phone: ["702-849-8239"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Combined Singles 22-35 years",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-4-3-2-1",
    Leader: "Anabel Martinez",
    Phone: ["702-624-2275"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-4-3-3-2",
    Leader: "Blas Duran",
    Phone: ["702-502-2773"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-4-4-1-1",
    Leader: "Alejandra Rodriguez",
    Phone: ["702-410-3674"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-4-4-1-2",
    Leader: "Margarita Hernandez",
    Phone: ["702-328-4825"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "R-4-4-2-2",
    Leader: "Antonio Fernandez",
    Phone: ["702-937-2613"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "R-4-4-3-1",
    Leader: "Isabel Calix",
    Phone: ["702-849-3085"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-1-1-3-2",
    Leader: "Armando y Olga Lopez",
    Phone: ["702-406-4311"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-1-2-2-1",
    Leader: "Gabriel Chavez",
    Phone: ["702-793-0131"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-1-3-2-2",
    Leader: "Jose A. Martinez",
    Phone: ["702-503-9660"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married With Children (14-21 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-1-4-1-1",
    Leader: "Alejandro Rubio",
    Phone: ["702-376-5660"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-1-4-1-2",
    Leader: "Antonio Hernandez",
    Phone: ["702-931-6657"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Married Without Children",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-2-2-4-1",
    Leader: "Dulce Sanchez",
    Phone: ["702-513-4475"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-2-3-1-2",
    Leader: "Ana Escobar",
    Phone: ["702-517-0798"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-2-3-5-1",
    Leader: "Maria Sandoval",
    Phone: ["702-628-4769"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["10:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-2-3-5-2",
    Leader: "Blanca Vargas",
    Phone: ["702-412-2784"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-2-5-2-1",
    Leader: "Basilio Martin",
    Phone: ["702-752-4259"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-2-5-2-2",
    Leader: "Maria C. Garcia",
    Phone: ["661-886-3358"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-2-5-3-1",
    Leader: "Pascasio y Lucina Martin",
    Phone: ["702-463-0341"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-3-1-1-1",
    Leader: "Judith Melgar",
    Phone: ["702-419-6193"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-3-1-2-1",
    Leader: "Marcos Berrut",
    Phone: ["702-919-9914"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-3-3-1-1",
    Leader: "Erika Beltran",
    Phone: ["702-675-0938"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-3-3-1-2",
    Leader: "Ismael Martin",
    Phone: ["702-494-9281"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Married With Children (14-21 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-3-4-1-2",
    Leader: "Rosa Nelson",
    Phone: ["702-370-0585"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-4-1-1-1",
    Leader: "Yessica Estrada",
    Phone: ["702-772-5150"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-4-1-1-2",
    Leader: "Jose Estrada",
    Phone: ["702-908-0326"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-4-2-1-1",
    Leader: "Juan Tiznado",
    Phone: ["725-600-1447"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-4-2-1-2",
    Leader: "Melina Marin",
    Phone: ["702-680-5966"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-4-2-2-1",
    Leader: "Cesar Solano",
    Phone: ["702-479-9082"],
    Campus: "Las Vegas",
    Days: "Wednesday/Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-4-2-3-1",
    Leader: "Lupita Solano",
    Phone: ["702-583-0952"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-5-1-1-1",
    Leader: "Veronica Castro",
    Phone: ["702-972-5308"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Female",
    Demographic: "Single Women (36-60 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-5-1-1-2",
    Leader: "Johony Ceron",
    Phone: ["702-755-3671"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-5-2-1-1",
    Leader: "Lidia Hernandez",
    Phone: ["702-759-3465"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-5-2-1-2",
    Leader: "Rosa Gonzalez",
    Phone: ["209-594-2823"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["11:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "S-5-3-1-1",
    Leader: "Conny Rendon",
    Phone: ["702-569-1662"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "S-5-3-1-2",
    Leader: "Ivania Moreno",
    Phone: ["702-287-6542"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-1-1-1",
    Leader: "Gina Cobas",
    Phone: ["702-758-0244"],
    Campus: "Las Vegas",
    Days: "Tuesday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["10:30 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-1-1-2",
    Leader: "Johanna Largaespada",
    Phone: ["661-916-1067"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-1-1-2-1",
    Leader: "Alex Gonzalez",
    Phone: ["702-533-6851"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-1-3-2",
    Leader: "Higinio Gomez",
    Phone: ["702-980-2713"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "SH-1-3-1-1",
    Leader: "Alejandra Osorio",
    Phone: ["323-504-0396"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Combined Singles 22-35 years",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-3-2-1",
    Leader: "Clara Nieto",
    Phone: ["702-541-5868"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-3-3-1",
    Leader: "Fabiola Esparza",
    Phone: ["702-824-7777"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic:
      "Married With Children (0-8 years) Married With Children (14-21 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-3-3-2",
    Leader: "Francisco Osorio",
    Phone: ["323-499-8288"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-1-3-4-1",
    Leader: "Cecilia Sheffer",
    Phone: ["702-773-9967"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["5:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-1-3-4-2",
    Leader: "Gerardo y Cristal Salas",
    Phone: ["702-401-2997"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Female",
    Demographic: "Single Women",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-3-5-1",
    Leader: "Cecilia Sheffer",
    Phone: ["702-773-9967"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["11:00 PM"],
    InPerson: "In-Person",
    Language: "Bilingual",
    Childcare: "No",
  },
  {
    Group: "SH-1-5",
    Leader: "Elena Gomez",
    Phone: ["702-488-5131"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-1-5-1-1",
    Leader: "Elena Gomez",
    Phone: ["702-488-5131"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["10:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-2-1-1-1",
    Leader: "Maria E.Herrera",
    Phone: ["702-675-0406"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-2-3-1-1",
    Leader: "Jorge Gonzalez",
    Phone: ["702-504-5736", "702-542-9347"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-2-3-1-2",
    Leader: "Laura Galvez",
    Phone: ["702-209-7964"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-2-3-3-1",
    Leader: "Cecilia Villalta",
    Phone: ["702-666-1052"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-2-4-1-1",
    Leader: "Roberto Salgado",
    Phone: ["562-477-1126"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-2-4-2-1",
    Leader: "Miriam Escalante",
    Phone: ["702-845-8333"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-2-4-2-2",
    Leader: "Oscar Perez",
    Phone: ["702-912-9042"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-3-1-1-1",
    Leader: "Erika Marin",
    Phone: ["702-418-4470"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-3-1-2-1",
    Leader: "Erika Marin",
    Phone: ["702-418-4470"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["9:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-3-2-1-1",
    Leader: "Jose Corral",
    Phone: ["702-300-6878"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["6:30 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-3-2-2-2",
    Leader: "Eliseo y Carmen Pascual",
    Phone: ["702-773-1150", "702-787-1547"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["8:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-3-3-1-1",
    Leader: "Alvin y Alicia Rodriguez",
    Phone: ["702-913-0006", "702-502-0743"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-3-3-2-1",
    Leader: "Rosa Zelaya",
    Phone: ["702-324-5373", "702-494-9239"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married Couples (Mixed)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-3-4-1-1",
    Leader: "Juan y Ruth Ventura",
    Phone: ["702-501-2847", "702-496-1780"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-3-4-1-2",
    Leader: "Norma Ramos y Francisco Sanchez",
    Phone: ["702-682-7147", "702-412-9191"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-3-5-1-1",
    Leader: "Juan Cuaya",
    Phone: ["702-771-8962", "702-773-5977"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-1-1-2",
    Leader: "Erick Castillo",
    Phone: ["702-773-5701"],
    Campus: "Las Vegas",
    Days: "Saturday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["10:00 AM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-1-2-2",
    Leader: "Norma Castillo",
    Phone: ["702-479-9331"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-4-1-4-1",
    Leader: "Angel Gonzalez",
    Phone: ["702-595-8579", "702-624-1281"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-2-1-2",
    Leader: "Olga y Jaime Leon",
    Phone: ["702-500-9433", "702-582-1006"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-3-1-2",
    Leader: "Martha Sotelo",
    Phone: ["702-809-6566"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-4-1-1",
    Leader: "Heraclio Antonio Zerafino",
    Phone: ["702-772-5886"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-4-5-2-2",
    Leader: "Yanet Rodriguez",
    Phone: ["702-980-6413"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-5-1-1-1",
    Leader: "Hedilberto Avalos",
    Phone: ["702-937-0043"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-5-1-1-2",
    Leader: "Carlos Acosta",
    Phone: ["702-609-1917"],
    Campus: "Las Vegas",
    Days: "Monday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["6:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
  {
    Group: "SH-5-2-1-1",
    Leader: "Jeorgina Torres Pena",
    Phone: ["702-504-7007"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married With Children (All ages)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-5-2-1-2",
    Leader: "Griselda Flores",
    Phone: ["702-217-1079"],
    Campus: "Las Vegas",
    Days: "Wednesday",
    Gender: "Combined",
    Demographic: "Married With Children (0-8 years)",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-5-2-1-2",
    Leader: "William Flores",
    Phone: ["702-858-0661"],
    Campus: "Las Vegas",
    Days: "Thursday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "Childcare",
  },
  {
    Group: "SH-5-3-2-1",
    Leader: "Claudia Elizabeth Aguilar",
    Phone: ["702-504-8017"],
    Campus: "Las Vegas",
    Days: "Friday",
    Gender: "Combined",
    Demographic: "Everyone Welcome",
    Time: ["7:00 PM"],
    InPerson: "In-Person",
    Language: "Spanish",
    Childcare: "No",
  },
];
